Controllers/ReteteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CookingHeaven.Data;
using CookingHeaven.Models;
using Microsoft.AspNetCore.Authorization;

namespace CookingHeaven.Controllers
{
    public class ReteteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReteteController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Retete
        public async Task<IActionResult> Index()
        {
            return View(await _context.Retete.ToListAsync());
        }

        // GET: Retete/CautaOReteta
        public async Task<IActionResult> CautaOReteta()
        {
            return View();
        }
        // POST: Retete/ArataRezultatul
        public async Task<IActionResult> ArataRezultatul(String NumeleRetetei)
        {
            return View("Index", await _context.Retete.Where(j =>j.RetetaNume.Contains(NumeleRetetei)).ToListAsync());
        }

        // GET: Retete/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var retete = await _context.Retete
                .FirstOrDefaultAsync(m => m.ID == id);
            if (retete == null)
            {
                return NotFound();
            }

            return View(retete);
        }

        // GET: Retete/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Retete/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RetetaNume,RetetaDescriere")] Retete retete)
        {
            if (ModelState.IsValid)
            {
                _context.Add(retete);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(retete);
        }
        [Authorize]
        // GET: Retete/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var retete = await _context.Retete.FindAsync(id);
            if (retete == null)
            {
                return NotFound();
            }
            return View(retete);
        }

        // POST: Retete/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,RetetaNume,RetetaDescriere")] Retete retete)
        {
            if (id != retete.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(retete);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReteteExists(retete.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(retete);
        }
        [Authorize]
        // GET: Retete/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var retete = await _context.Retete
                .FirstOrDefaultAsync(m => m.ID == id);
            if (retete == null)
            {
                return NotFound();
            }

            return View(retete);
        }

        // POST: Retete/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var retete = await _context.Retete.FindAsync(id);
            _context.Retete.Remove(retete);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReteteExists(int id)
        {
            return _context.Retete.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CookingHeaven</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CookingHeaven</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Retete" asp-action="Index">Retete</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Retete" asp-action="CautaOReteta">Cauta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Tutorial">Ghid</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CookingHeaven
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>